### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by mgedmin** [zopefoundation/z3c.testsetup#1]
This blocks https://github.com/zestsoftware/zest.releaser/issues/5

**Comment by mgedmin** [comment]
aaand this is blocked by [martian](https://pypi.python.org/pypi/martian) not having Python 3 support.

(And then I foresee Lots Of Fun with zope.app.testing's ZCMLLayer.)

**Comment by mgedmin** [comment]
Oh, look, here's https://github.com/zopefoundation/martian/pull/1

**Comment by ulif** [comment]
Just stumbled over that and feel guilty about the mess. If it is still a problem (for other packages), I might try my luck. Just in case. Shall I?

**Comment by reinout** [comment]
Realistically, zest.releaser should not be using z3c.testsetup. Even though I was probably the one that introduced it :-) (I didn't check).

IF it isn't too great an effort, it might be worth a try, though. Whether it is worth it depends on how much it is used by other packages.

**Comment by ulif** [comment]
Thanks for the feedback, Reinout!

Generally, I also would recommend to remove z3c.testsetup dependencies whereever possible.

Apart from that I will give it a try tomorrow. If it turns out, things are too difficult (esp. z.a.testing stuff) I will know by tomorrow evening.

**Comment by ulif** [comment]
After a quick scan: because z3c.testsetup does not strictly rely on zope.app.testing being available at runtime, it _can_ be made 3.x compatible. As long as zope.app.testing is not py3-ready, respective tests would be ignored, but, well, that's all we can get. z.a.testing is the only real burden here.
I will start the transform tomorrow.

**Comment by ulif** [comment]
0.8.4 is out with support for py33, py34 and pypy. I hope that fixes blocking of other packages.
