### ISSUE TITLE
Test against Python 3 on TravisCI

### ISSUE THREAD

**Issue by icemac** [zopefoundation/z3c.testsetup#2]
The package seems to support Python 3 but it is not tested on TravisCI.
See https://travis-ci.org/zopefoundation/z3c.testsetup/builds/443423992

**Comment by jugmac00** [comment]
Currently all tests fail - also Py3 (local in tox).

Is this a candidate for archiving?

Pinging @reinout @mgedmin

**Comment by mgedmin** [comment]
```
mg@blynas: ~/src/zopefoundation $ rg -l z3c.testsetup|grep -v ^z3c.testsetup
```
shows that z3c.testsetup was once used by groktoolkit, but is no longer used.  The only remaining references are in the documentation.

There are no other references.

I've never used z3c.testsetup myself.

**Comment by jugmac00** [comment]
Thanks, Marius!

@icemac - please hit the `nuke` button :-D

**Comment by icemac** [comment]
Okay, going to archive it.
